### ISSUE TITLE
is it not possible to insert api key

### ISSUE THREAD

**Issue by manoelacmn** [yonashailug/chatgpt-cli#2]
i am  unable to insert my api key,not even after deleting it and cleaning the cache,it simply doesn't request the api key and neither there's a flag option to use.

**Comment by yonashailug** [comment]
@manoelacmn thank you for rising the issue. Now you can enter the api key by using `chatgpt-cli -k` command.

Additionally, you can find the api key below path
>  ~/.config/configstore/@yonashailug/chatgpt-cli.json
